#!/bin/bash

DIR_HERE=$(dirname $(realpath $0))
DIR_REPO=$DIR_HERE/../
cd $DIR_REPO

docker compose exec postgis bash -c "psql -h localhost -U \$POSTGRES_USER -d \$POSTGRES_DB"
# docker compose exec postgis bash -c "psql -h localhost -U \$POSTGRES_USER -P \$POSTGRES_PASSWORD -d \$POSTGRES_DB"
